name: dessert_bantaeng

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '54.206.45.136'
          username: 'root'
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Hapus Node.js versi lama dan konflik
            sudo apt purge -y nodejs npm libnode-dev
            sudo apt autoremove -y
            
            # 2. Install Node.js 22.x dengan clean state
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt install -y nodejs
            
            # 3. Verifikasi instalasi
            node -v
            npm -v
            
            # 4. Install global dependencies
            sudo npm install -g npm@latest pm2
            
            # 5. Bersihkan perubahan lokal di repo
            cd /home/ubuntu/app_kurier_server
            git reset --hard
            git clean -fd
            
            # 6. Update repo
            git config --global --add safe.directory /home/ubuntu/app_kurier_server
            git pull origin main
            
            # 7. Install dependencies dan restart aplikasi
            cd src
            npm install
            pm2 delete bantaeng_dessert || true
            pm2 start ./server.js -n bantaeng_dessert