name: dessert_bantaeng
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '54.206.45.136'
          username: 'ubuntu'
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Fix Node.js installation
            curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt purge -y nodejs npm
            sudo apt install -y nodejs

            # Update npm & install PM2
            sudo npm install -g npm@latest
            sudo npm install -g pm2

            # Prepare project directory
            git config --global --add safe.directory /home/ubuntu/app_kurier_server
            cd /home/ubuntu/app_kurier_server/src
            git pull origin main
            npm install  # Install dependencies

            # Restart PM2 process
            pm2 delete bantaeng_dessert || true
            pm2 start ./server.js -n bantaeng_dessert