# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI/CD

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: self-hosted
#     strategy:
#       matrix:
#         node-version: [22.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: |
#           touch .env
#           echo "${{ secrets.PROD_ENV_FILE }}" > .env


name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30  # Batasi waktu maksimal execution

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    # Cache optimization
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --prefer-offline
    
    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
        # Pastikan file .env memiliki permission yang tepat
        chmod 600 .env
    
    - name: Build application
      run: npm run build --if-present
    
    - name: Restart PM2 process
      run: |
        pm2 delete "app_dessert" || true
        pm2 start npm --name "app_dessert" -- start
